name: Deploy static HTML site

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create deploy folder
      run: |
        mkdir deploy/
        cp -r css/ fonts/ images/ js/ index.html saisie-temps.html faits-marquants.html  deploy/ dist/

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: deploy/

    - name: Deploy to Github pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy
